name: build kicad-render image
on:
  workflow_dispatch:
  push:
    paths:
    - Dockerfile
    - '*.sh'
    - .github/workflows/image.yaml
    - .github/workflows/tests
    - action.yaml

jobs:

  push_to_registry:
    name: Build, Test and Push
    runs-on: ubuntu-latest
    env:
      docker_image: ghcr.io/kekcheburec/kicad-render:${{ github.ref_name }}
      docker_image_cache: ghcr.io/kekcheburec/kicad-render:cache-${{ github.ref_name }}
      docker_file: ./Dockerfile

    permissions:
      packages: write
      contents: read

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Get current date
        id: date
        run:  echo "date=$(date +'%Y-%m-%d-%H-%M')" >> $GITHUB_OUTPUT

      - name: Build and push Docker image dev
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ env.docker_file }}
          build-args: |
            "VERSION=${{ github.sha }}"
          cache-to: "type=registry,ref=${{ env.docker_image_cache }}"
          cache-from: "type=registry,ref=${{ env.docker_image_cache }}"
          load: true
          tags: "${{ env.docker_image }}"
          platforms: linux/amd64
          privileged: true

      - name: simple render
        run: docker run --privileged -v ${GITHUB_WORKSPACE}:/pwd --rm ${{ env.docker_image }} render-pcb.sh -f "/pwd/.github/tests/test pcb/troyka-base-module.kicad_pcb"
      - name: simple render - test file created
        run: test -s "${GITHUB_WORKSPACE}/.github/tests/test pcb/troyka-base-module_top.png"

      - name: replace docker image with branch image
        run: sed -i 's#ghcr.io/kekcheburec/kicad-render.*$#${{ env.docker_image }}#g' ${GITHUB_WORKSPACE}/action.yaml && cat ${GITHUB_WORKSPACE}/action.yaml 
      
      - name: Archive test renders
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-renders
          path: ${{ github.workspace }}/images

      - name: push docker image dev
        if: github.ref_name != github.event.repository.default_branch
        run: |
          docker tag ${{ env.docker_image }} ghcr.io/kekcheburec/kicad-render:9-dev-${{ github.ref_name }}
          docker tag ${{ env.docker_image }} ghcr.io/kekcheburec/kicad-render:9-dev-${{ steps.date.outputs.date }}
          docker push ghcr.io/kekcheburec/kicad-render:9-dev-${{ github.ref_name }}
          docker push ghcr.io/kekcheburec/kicad-render:9-dev-${{ steps.date.outputs.date }}

      - name: push docker image
        if: github.ref_name == github.event.repository.default_branch
        run: |
          docker tag ${{ env.docker_image }} ghcr.io/kekcheburec/kicad-render:9
          docker tag ${{ env.docker_image }} ghcr.io/kekcheburec/kicad-render:9-${{ steps.date.outputs.date }}
          docker push ghcr.io/kekcheburec/kicad-render:9
          docker push ghcr.io/kekcheburec/kicad-render:9-${{ steps.date.outputs.date }}